CREATE PROCEDURE SP_ADD_LOCACOES
@COD_CLIENTE INT,
@COD_FILME INT,
@DATA_LOCACAO DATETIME

AS 
BEGIN
	DECLARE @QTD_ALOCADO INT
	SET @QTD_ALOCADO = (SELECT COUNT(*) FROM LOCACOES WHERE COD_CLIENTE = @COD_CLIENTE)
	IF @QTD_ALOCADO < 5
	BEGIN
		DECLARE @VALOR_LOCACAO FLOAT
		DECLARE @COD_CATEGORIA INT
		DECLARE @DIAS_PRA_DEVOLVER SMALLINT
		DECLARE @DATA_PRA_DEVOLVER DATETIME

		SET @COD_CATEGORIA = (SELECT COD_CATEGORIA FROM FILMES WHERE COD_FILME = @COD_FILME)
		SET @VALOR_LOCACAO = (SELECT VALOR FROM CATEGORIAS WHERE COD_CATEGORIA = @COD_CATEGORIA)
		SET @DIAS_PRA_DEVOLVER = (SELECT DIAS_PRA_DEVOLVER FROM CATEGORIAS WHERE COD_CATEGORIA = @COD_CATEGORIA)
		SET @DATA_PRA_DEVOLVER = @DATA_LOCACAO+@DIAS_PRA_DEVOLVER

		UPDATE CLIENTES SET
			VALOR_DEVIDO = VALOR_DEVIDO + @VALOR_LOCACAO
			WHERE COD_CLIENTE = @COD_CLIENTE
		INSERT INTO LOCACOES (COD_CLIENTE,COD_FILME,VALOR_LOCACAO,DATA_LOCACAO,DATA_A_DEVOLVER)
		VALUES (@COD_CLIENTE,@COD_FILME,@COD_FILME,@VALOR_LOCACAO,@DATA_LOCACAO,@DATA_PRA_DEVOLVER)
		PRINT('VIDEO LOCADO COM SUCESSO!')
	END
	ELSE BEGIN
		PRINT('CLIENTE JA POSSUI 5 OU MAIS VIDEOS LOCADOS')
		RETURN
	END
END
