CREATE PROCEDURE SP_DEVOLUCAO
@COD_FILME INT,
@DATA_DEVOLUCAO DATETIME

AS BEGIN
	DECLARE @DIAS_ATRASO INT
    DECLARE @DATA_A_DEVOLVER DATETIME
	DECLARE @VALOR_DEVIDO FLOAT
	DECLARE @COD_CLIENTE INT

	SET @COD_CLIENTE = (SELECT COD_CLIENTE FROM LOCACOES WHERE COD_FILME = @COD_FILME AND DATA_DEVOLUCAO = @DATA_DEVOLUCAO)
	SET @DATA_A_DEVOLVER = (SELECT DATA_A_DEVOLVER FROM LOCACOES WHERE COD_FILME = @COD_FILME AND DATA_DEVOLUCAO = @DATA_DEVOLUCAO)
	SET @DIAS_ATRASO = DATEDIFF(DAY, @DATA_A_DEVOLVER, @DATA_DEVOLUCAO)
	SET @VALOR_DEVIDO = 2 * @DIAS_ATRASO

	UPDATE CLIENTES SET 
	VALOR_DEVIDO = @VALOR_DEVIDO
	WHERE COD_CLIENTE = @COD_CLIENTE
	
	PRINT('DEVOLUCAO FEITA COM SUCESSO')
END
