CREATE PROCEDURE SP_PAGAR_LOCACAO
@COD_LOCACAO INT,
@DATA_PAGO DATETIME,
@VALOR_PAGO FLOAT

AS BEGIN
	DECLARE @PAGO SMALLINT
	DECLARE @VALOR_DEVIDO FLOAT
	DECLARE @COD_CLIENTE INT
	DECLARE @VALOR_SOBRADO FLOAT

	SET @COD_CLIENTE = (SELECT COD_CLIENTE FROM LOCACOES WHERE COD_LOCACAO = @COD_LOCACAO)
	SET @VALOR_DEVIDO = (SELECT VALOR_DEVIDO FROM CLIENTES WHERE @COD_CLIENTE = @COD_CLIENTE)
	SET @VALOR_SOBRADO = @VALOR_DEVIDO - @VALOR_PAGO

	IF @VALOR_SOBRADO < 0 
		BEGIN 
			SET @VALOR_SOBRADO = 0
		END
		UPDATE CLIENTES SET
		VALOR_DEVIDO = @VALOR_SOBRADO
		WHERE COD_CLIENTE = @COD_CLIENTE
		IF @VALOR_SOBRADO = 0
		BEGIN
		UPDATE LOCACOES SET
		DEVOLVIDO = 1,
		DATA_PAGO = @DATA_PAGO,
		VALOR_PAGO = @VALOR_PAGO
		WHERE COD_LOCACAO = @COD_LOCACAO
	
		PRINT('LOCACAO PAGO COM SUCESSO')
	ELSE 
		BEGIN	
			PRINT('LOCACAO PAGO MAIS AINDA FALTAM PAGAR '+ VALOR_SOBRADO)
		END
END
