CREATE PROCEDURE SP_ADD_CATEGORIAS
@DESCRICAO VARCHAR(100),
@VALOR FLOAT,
@DIAS_PRA_DEVOLVER SMALLINT
AS BEGIN
	DECLARE @CONT INT

	SET @CONT = (SELECT COUNT(*) FROM CATEGORIAS)
	SET @CONT = @CONT + 1

	IF @DESCRICAO = '' OR @DESCRICAO IS NULL
	BEGIN
		SET @DESCRICAO = 'CATEGORIA '+(CAST(@CONT AS VARCHAR))
	END
	INSERT INTO CATEGORIAS (DESCRICAO,VALOR,DIAS_PRA_DEVOLVER)
	VALUES (@DESCRICAO,@VALOR,@DIAS_PRA_DEVOLVER)
	
	PRINT('A CATEGORIA FOI INSERIDA COM SUCESSO')
END
