CREATE PROCEDURE SP_DEL_FILME
@COD_FILME INT
AS BEGIN
	DECLARE @TITULO VARCHAR
	DECLARE @COD_CATEGORIA INT
	DECLARE @DATA_HORA DATETIME
	
	SET @TITULO = (SELECT TITULO FROM FILMES WHERE COD_FILME = @COD_FILME)
	SET @COD_CATEGORIA = (SELECT COD_CATEGORIA FROM FILMES WHERE COD_FILME = @COD_FILME)
	SET @DATA_HORA = GETDATE()

	INSERT INTO FILMES_EXCLUIDOS (COD_FILME,TITULO,COD_CATEGORIA,DATA_HORA)
	VALUES (@COD_FILME,@TITULO,@COD_CATEGORIA,@DATA_HORA)

	DELETE FROM FILMES WHERE COD_FILME = @COD_FILME

	PRINT('FILME DELETADO COM SUCESSO')
END
