import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author julio
 */
public class Cliente extends javax.swing.JFrame {

  private JTextField txtIP, txtPorta, txtNome;
  private Socket socket;
  private OutputStream ou;
  private Writer ouw;
  private BufferedWriter bfw;

  /**
   * Creates new form NewJFrame
   */
  public Cliente() {
    initComponents();

    JLabel lblMsg = new JLabel("Informações de conexão");
    this.txtIP = new JTextField("127.0.0.1");
    this.txtPorta = new JTextField("12345");
    this.txtNome = new JTextField("nome_cliente");
    Object[] aux = { lblMsg, txtIP, txtPorta, txtNome };
    JOptionPane.showMessageDialog(null, aux);
    this.setTitle(txtNome.getText());
    this.setResizable(false);
    this.setVisible(true);
  }

  public void conectar() {
    try {
      this.socket =
        new Socket(
          this.txtIP.getText(),
          Integer.parseInt(this.txtPorta.getText())
        );
      this.ou = this.socket.getOutputStream();
      this.ouw = new OutputStreamWriter(this.ou);
      this.bfw = new BufferedWriter(this.ouw);
      this.bfw.write(this.txtNome.getText() + "\n");
      this.bfw.flush();
    } catch (IOException ex) {
      Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  public void enviarMensagem(String msg) {
    try {
      this.bfw.write(msg + "\n");
      this.bfw.flush();
      this.txtHistorico.append("Você: " + msg + "\n");
      this.txtMsg.setText("");
    } catch (IOException ex) {
      Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  public void escutar() {
    try {
      InputStream in = this.socket.getInputStream();
      InputStreamReader inr = new InputStreamReader(in);
      BufferedReader bfr = new BufferedReader(inr);
      String msg = "";

      while (!msg.equalsIgnoreCase("sair")) {
        if (bfr.ready()) {
          msg = bfr.readLine();
          System.out.println(msg);
          this.txtHistorico.append(msg + "\n");
        }
      }
    } catch (IOException ex) {
      Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    btnEnviar = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtHistorico = new javax.swing.JTextArea();
    jPanel2 = new javax.swing.JPanel();
    txtMsg = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(
      new java.awt.event.WindowAdapter() {
        public void windowClosed(java.awt.event.WindowEvent evt) {
          formWindowClosed(evt);
        }
      }
    );

    btnEnviar.setText("Enviar");
    btnEnviar.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnEnviarActionPerformed(evt);
        }
      }
    );

    btnSair.setText("Sair");
    btnSair.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnSairActionPerformed(evt);
        }
      }
    );

    jPanel1.setBorder(
      javax.swing.BorderFactory.createTitledBorder(
        null,
        "Histórico",
        javax.swing.border.TitledBorder.CENTER,
        javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new java.awt.Font("Tahoma", 1, 11)
      )
    ); // NOI18N

    txtHistorico.setColumns(20);
    txtHistorico.setRows(5);
    jScrollPane1.setViewportView(txtHistorico);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
      jPanel3
    );
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanel3Layout
            .createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              215,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
        )
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jPanel3,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addContainerGap()
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jPanel3,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addContainerGap()
        )
    );

    jPanel2.setBorder(
      javax.swing.BorderFactory.createTitledBorder(
        null,
        "Mensagem",
        javax.swing.border.TitledBorder.CENTER,
        javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new java.awt.Font("Tahoma", 1, 11)
      )
    ); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
      jPanel2
    );
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(txtMsg)
            .addContainerGap()
        )
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanel2Layout
            .createSequentialGroup()
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(
              txtMsg,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap()
        )
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jPanel1,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jPanel2,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(
                      btnSair,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      181,
                      Short.MAX_VALUE
                    )
                    .addGap(18, 18, 18)
                    .addComponent(
                      btnEnviar,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      181,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jPanel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(
              jPanel2,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              26,
              Short.MAX_VALUE
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(btnSair)
                    .addGap(20, 20, 20)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(btnEnviar)
                    .addGap(19, 19, 19)
                )
            )
        )
    );

    jPanel2.getAccessibleContext().setAccessibleName("Mensagem");

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnEnviarActionPerformed
    // TODO add your handling code here:
    enviarMensagem(txtMsg.getText());
  } //GEN-LAST:event_btnEnviarActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnSairActionPerformed
    // TODO add your handling code here:
    this.dispose();
  } //GEN-LAST:event_btnSairActionPerformed

  private void formWindowClosed(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_formWindowClosed
    // TODO add your handling code here:
    sair();
  } //GEN-LAST:event_formWindowClosed

  public void sair() {
    try {
      enviarMensagem("sair");
      this.bfw.close();
      this.ouw.close();
      this.ou.close();
      this.socket.close();
    } catch (IOException ex) {
      Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(Cliente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(Cliente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(Cliente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(Cliente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    Cliente c = new Cliente();
    c.conectar();
    c.escutar();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          //new Cliente().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEnviar;
  private javax.swing.JButton btnSair;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtHistorico;
  private javax.swing.JTextField txtMsg;
  // End of variables declaration//GEN-END:variables
}
