p(a,c).
p(a,b).
p(d,a).
p(d,b).

homem(rui).
homem(miguel).
homem(pedro).
homem(joao).
homem(jose).
mulher(ana).
mulher(manuela).
mulher(joana).
mulher(rita).
casados(ana,rui).
casados(manuela,miguel).
casados(joana,pedro).
descendentes(miguel,ana,rui).
descendentes(joana,ana,rui).
descendentes(rita,joana,pedro).
descendentes(joao,joana,pedro).
descendentes(jose,joana,pedro).
pai(P,F):=descendentes(F,_,P).
mae(M,F):=descendentes(F,M,_).
