ALTER TRIGGER TR_UPD_MOVTO
ON MOVIMENTACAO
FOR UPDATE
AS 
BEGIN
	DECLARE @COD_CLIENTE INT,@COD_CLIENTE_D INT, @TIPO_MOVTO CHAR(1), @TIPO_MOVTO_D CHAR(1), @VALOR FLOAT,@VALOR_D FLOAT
	

	SELECT  @COD_CLIENTE = COD_CLIENTE,
			@TIPO_MOVTO = TIPO_MOVTO,
			@VALOR = ISNULL(VALOR,0)
		FROM DELETED

	SELECT	@COD_CLIENTE_D = COD_CLIENTE,
			@VALOR_D = ISNULL(VALOR,0), 
			@TIPO_MOVTO_D = TIPO_MOVTO
	FROM INSERTED

	IF @COD_CLIENTE <> @COD_CLIENTE_D
		BEGIN
			IF @TIPO_MOVTO = 'C' OR @TIPO_MOVTO = 'c'
				BEGIN
					UPDATE CLIENTES 
						SET SALDO = SALDO - @VALOR 
					WHERE COD_CLIENTE = @COD_CLIENTE
				END
			IF @TIPO_MOVTO = 'D' OR @TIPO_MOVTO = 'd'
				BEGIN
					UPDATE CLIENTES 
						SET SALDO = SALDO + @VALOR 
					WHERE COD_CLIENTE = @COD_CLIENTE
				END

			SET @COD_CLIENTE = @COD_CLIENTE_D
		END
	
	IF @VALOR <> @VALOR_D
		BEGIN
			
			IF (@TIPO_MOVTO = 'D' OR @TIPO_MOVTO = 'd') AND (@TIPO_MOVTO_D = 'C' OR @TIPO_MOVTO_D = 'c')
				BEGIN
					UPDATE CLIENTES 
					SET SALDO = SALDO + @VALOR 
					WHERE COD_CLIENTE = @COD_CLIENTE

					SET @TIPO_MOVTO = @TIPO_MOVTO_D;
				END

			IF (@TIPO_MOVTO = 'C' OR @TIPO_MOVTO = 'c') AND (@TIPO_MOVTO_D = 'D' OR @TIPO_MOVTO_D = 'd')
				BEGIN
					UPDATE CLIENTES 
						SET SALDO = SALDO - @VALOR 
					WHERE COD_CLIENTE = @COD_CLIENTE

					SET @TIPO_MOVTO = @TIPO_MOVTO_D;
				END

			IF @TIPO_MOVTO = 'C' OR @TIPO_MOVTO = 'c'
				BEGIN
					UPDATE CLIENTES 
						SET SALDO = SALDO  + (@VALOR_D - @VALOR) 
					WHERE COD_CLIENTE = @COD_CLIENTE							
				END
			IF @TIPO_MOVTO = 'D' OR @TIPO_MOVTO = 'd'
				BEGIN
					UPDATE CLIENTES 
						SET SALDO = SALDO - (@VALOR_D - @VALOR) 
					WHERE COD_CLIENTE = @COD_CLIENTE

				
				END
		END	
		ELSE
			BEGIN
				IF (@TIPO_MOVTO = 'D' OR @TIPO_MOVTO = 'd') AND (@TIPO_MOVTO_D = 'C' OR @TIPO_MOVTO_D = 'c')
					BEGIN
						UPDATE CLIENTES 
						SET SALDO = SALDO + @VALOR 
						WHERE COD_CLIENTE = @COD_CLIENTE

						SET @TIPO_MOVTO = @TIPO_MOVTO_D;
				END

				IF (@TIPO_MOVTO = 'C' OR @TIPO_MOVTO = 'c') AND (@TIPO_MOVTO_D = 'D' OR @TIPO_MOVTO_D = 'd')
					BEGIN
						UPDATE CLIENTES 
							SET SALDO = SALDO - @VALOR 
						WHERE COD_CLIENTE = @COD_CLIENTE

						SET @TIPO_MOVTO = @TIPO_MOVTO_D;
				END
			END
END