CREATE FUNCTION RETORNA_TABELA_NOME()
RETURNS @TBLF TABLE(SEQUENCIA INT IDENTITY(1,1),NOME VARCHAR(50))
AS
BEGIN
	
	INSERT INTO @TBLF(NOME)VALUES('VINICIUS');
	INSERT INTO @TBLF(NOME)VALUES('MESQUINI');
	INSERT INTO @TBLF(NOME)VALUES('DE');
	INSERT INTO @TBLF(NOME)VALUES('OLIVEIRA');
	
	RETURN

END