CREATE PROCEDURE SP_UPD_MARCAS

@COD_MARCA INT,
@DESCRICAO	VARCHAR(50)

AS
IF EXISTS(SELECT * FROM marcas WHERE cod_marca = @COD_MARCA)
	IF NOT EXISTS (SELECT * FROM marcas M WHERE M.DESCRICAO = @DESCRICAO AND M.cod_marca <> @COD_MARCA)
	BEGIN
		UPDATE marcas SET descricao = @DESCRICAO WHERE cod_marca = @COD_MARCA;
		PRINT ('REGISTRO ATUALIZADO COM SUCESSO');
		RETURN 1;
	END
	ELSE
	BEGIN
		PRINT ('JÁ EXISTE ESSE REGISTRO');
		RETURN 0;
	END
ELSE
	PRINT ('CODIGO INVALIDO');
	RETURN 0;


