ALTER PROCEDURE SP_UPD_PRODUTOS

@COD_PRODUTO	INT,
@DESCRICAO		VARCHAR(50),
@VALOR_UNITARIO FLOAT,
@UNIDADE		CHAR(10),
@COD_MARCA		INT,
@QDE_ESTOQUE	FLOAT

AS
IF EXISTS(SELECT * FROM produtos WHERE cod_produto = @COD_PRODUTO)
	IF NOT EXISTS (SELECT * FROM produtos P WHERE P.descricao = @DESCRICAO AND P.cod_produto <> @COD_PRODUTO)
		BEGIN
			UPDATE produtos SET descricao = @DESCRICAO, valor_unitario = @VALOR_UNITARIO, unidade = @UNIDADE, 
								cod_marca = @COD_MARCA, qde_estoque = @QDE_ESTOQUE;
			PRINT ('REGISTRO ATUALIZADO COM SUCESSO');
			RETURN 1;
		END
	 ELSE
		BEGIN
			PRINT ('JÁ EXISTE ESSE REGISTRO');
			RETURN 0;
		END
ELSE
	PRINT ('CODIGO INVALIDO');
	RETURN 0;
