CREATE PROCEDURE SP_UPD_NOTA_FISCAL

@NUM_NOTA		INT,
@COD_CLIENTE	INT

AS

DECLARE @DATA DATE =  GETDATE();

IF EXISTS(SELECT * FROM nota_fiscal WHERE num_nota = @NUM_NOTA)
	BEGIN
		UPDATE nota_fiscal SET cod_cliente = @COD_CLIENTE, data = @DATA;
		PRINT ('REGISTRO ATUALIZADO COM SUCESSO');
		RETURN 1;
	END

ELSE
	BEGIN
		PRINT ('CODIGO INVALIDO');
		RETURN 0;
	END
