ALTER PROCEDURE SP_UPD_CLIENTE

@COD_CLIENTE INT,
@NOME		VARCHAR(50),
@CPF		VARCHAR(13),
@ENDERECO	VARCHAR(50),
@BAIRRO		VARCHAR(20),
@COD_CIDADE INT,
@CEP		VARCHAR(9),
@TELEFONE	VARCHAR(15),
@CELULAR	VARCHAR(15)

AS

DECLARE @DATA_CADASTRO DATE  = GETDATE();

IF EXISTS(SELECT * FROM clientes WHERE cod_cliente = @COD_CLIENTE)

	IF NOT EXISTS (SELECT * FROM clientes C WHERE C.cod_cliente <> @COD_CLIENTE AND C.cpf = @CPF)
		BEGIN
			UPDATE clientes SET nome = @NOME, cpf = @CPF, endereco = @ENDERECO, bairro = @BAIRRO, cod_cidade = @COD_CIDADE,
								cep = @CEP, telefone = @TELEFONE, celular = @CELULAR, data_cadastro = @DATA_CADASTRO  
							WHERE cod_cliente = @COD_CLIENTE;
				
			PRINT ('REGISTRO ATUALIZADO COM SUCESSO');
			RETURN 1;
		END
	ELSE
		BEGIN
			PRINT ('JÁ EXISTE ESSE CPF EM OUTRO REGISTRO');
			RETURN 0;
		END
ELSE
	PRINT ('CODIGO INVALIDO')
	RETURN 0;
